// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "zero/order/api/internal/handler/order"
	"zero/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/order/getOrder",
				Handler: order.GetOrderHandler(serverCtx),
			},
		},
	)
}
